### PR TITLE
WIP: generic number type2

### PR DESCRIPTION
**Pull request by goretkin**
work in progress, not ready for merging

continuing from here: https://github.com/ApproxFun/ApproxFun.jl/pull/71

I have made a mistake in writing `chebyshevtransform` in terms of fft and was hoping for help. As far as I can tell, the `fft_gen` and `ifft_gen` functions are working properly. I wrote `chebyshevtransform` to match https://github.com/chebfun/chebfun/blob/master/@chebtech2/vals2coeffs.m , but I didn't really understand what I was doing.

``` julia
julia> n = 8; r = BigFloat[BigFloat(r) for r in rand(n,)];

julia> maximum( abs(chebyshevtransform(r) - chebyshevtransform(float64(r))) )
9.025352232940452587915806506104435996422000032418633430176793848182664747881608e-02 with 256 bits of precision
```

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Does interval arithmetic fall into this framework?  I guess it needs a good interval data type.

The nice thing about \ being based on Givens is that it should work well with interval arithmetic.  So it might not be hard to get rigorous solutions.

**Comment by goretkin** [comment]
I think it should. I've taken some derivatives by making Funs whose
coefficients are Dual numbers.

**Comment by dlfivefifty** [comment]
Cool!

I wonder if one can use \ for anything useful with Dual numbers.

**Comment by MikaelSlevinsky** [comment]
Section 6 in this (long) preprint is on the subject of obtaining rigorous bounds on the solutions via reformulation as an integral equation, though from the sounds of this thread the idea is to incorporate it directly into the adaptive QR. Anyways, food for thought. http://arxiv.org/abs/1407.2802

**Pull request merged**
