### PR TITLE
Update resizedata! with RaggedMatrix

### PR DESCRIPTION
**Pull request by johnwormell**
Fixed resizedata! so that resized RaggedMatrices have at least as many rows (.m field) as you ask to have (if you provide an integer number of rows), and preserve the existing datasize (if you provide a Colon).

### CODE REVIEW

**Comment by dlfivefifty** [comment]
This isn't quite right: you specify the number of columns, where K corresponds to the maximum number of rows.  I think in the for loop it should be

```julia
            for j = B.datasize[2]+1:n-1
                cs = colstop(B.op,j)
                B.data.cols[j+1] = B.data.cols[j] + cs
                K = max(K,cs)
            end
```

to correctly calculate the maximum colstop.

**Comment by dlfivefifty** [comment]
Also, a CachedOperator is meant to always represent the underlying operator, so the number of rows in the ragged matrix is not really used.  This is why the resizedata!(A,n::Integer,m::Integer) seems wrong.

What's your use case?

**Comment by johnwormell** [comment]
Ah, cool. In any case, what I was trying to do seems to break some other things too!

My use case is viewing entries of the operator below the RaggedMatrix's ragged edge: these are zero of course, but attempting to access them (e.g. in showing ragged-below operators) gives you an error.

**Comment by dlfivefifty** [comment]
OK, maybe we want this (sorry the code is inconsistent between n x m and n x m dimensions):

```julia
function resizedata!{T<:Number}(B::CachedOperator{T,RaggedMatrix{T}},n::Integer,m::Integer)
    resizedata!(B,:,m)
    B.data.m = max(B.data.m,n)   # make sure we have at least n rows
end
```

**Comment by johnwormell** [comment]
Yes, looks like that works!

**Comment by dlfivefifty** [comment]
Can you update the pull request (just push to the branch) and add a unit test, please?

**Comment by johnwormell** [comment]
OK should be good to go I hope

**Comment by dlfivefifty** [comment]
Have you checked that the tests pass? Travis is throwing an error, though I'm not sure what the culprit is.  (It might be some other change but development is not seeing the same error)

**Comment by dlfivefifty** [comment]
PS some of the changes I've made today might have broken the tests.  Just in case this confuses you why the tests fail if you merge back development.

**Comment by johnwormell** [comment]
OK, cool. So I've made the above changes (and also fixed a couple of bugs in how resizedata!(B,:,m) calculates B.data.m), and added a unit test in Operators.jl.

**Comment by dlfivefifty** [comment]
Thanks a lot John!  I'll merge this as soon as my changes stabilize.  (I made the mistake of adding `…operatortest` routines that run a bunch of tests on a specified operator, which of course found numerous bugs.)

**Pull request merged**
