### PR TITLE
Make optional package loading much more precompilation compatible.

### PR DESCRIPTION
**Pull request by yuyichao**
* Add support for packages installed in LOAD_PATH
* Enable nightly on travis

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Thanks for this!  How much longer does it take to call

```using ApproxFun```

with this change, since it has to load all the dependencies?  The original reason for the lazy imports was how slow Gadfly is, but maybe since its precompiled this is no longer an issue.

**Comment by dlfivefifty** [comment]
Sorry for taking so long to merge this, but I think I'm going to first switch to using Plots.jl, which will remove many of the dependencies.

**Comment by yuyichao** [comment]
> The original reason for the lazy imports was how slow Gadfly is, but maybe since its precompiled this is no longer an issue.

I was actually mainly thinking about this issue. The import time is much longer and I think it might have to wait for the optinal submodule feature to be implemented in the base for this to be plausible.

**Comment by dlfivefifty** [comment]
Plots.jl seems to have its own lazy import implemented, so switching over will keep the current speed, and make the optional submodule feature @tbreloff’s problem 😀

**Comment by dlfivefifty** [comment]
Now that I've switch to Plots.jl, the PR is not needed anymore.

**Pull request closed without merging**
