### PR TITLE
BigFloat Cooley-Tukey FFT and Interval invariance

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
for Hilbert(d,0). Also, adding a small comment on the Σ operator, and renamed
the file.

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
Hi,

With @03964869acfe8025cea0a76b14b242d79b033f83, I was able to speed up the FFTs. I'm finding these timings now. Basically, 30% faster generic and the power of 2 is inline with Julia's dftnew branch.

```julia
julia> using ApproxFun

julia> bf = [big(f) for f in rand(5000,)];

julia> @time ApproxFun.fft_gen(bf);
elapsed time: 3.803332435 seconds (445958384 bytes allocated, 39.94% gc time)

julia> @time ApproxFun.fft_gen(bf);
elapsed time: 2.99054331 seconds (408197608 bytes allocated, 50.71% gc time)

julia> bf = [big(f) for f in rand(50000,)];

julia> @time ApproxFun.fft_gen(bf);
elapsed time: 91.160275884 seconds (7915675016 bytes allocated, 62.34% gc time)

julia> bf = [big(f) for f in rand(2^15,)];

julia> @time ApproxFun.fft_gen(bf);
elapsed time: 2.619733203 seconds (268306808 bytes allocated, 62.86% gc time)
```

**Comment by goretkin** [comment]
awesome! so do we need a separate implementation for `BigFloat`, or can we just have a `T<:Number` implementation?

**Comment by MikaelSlevinsky** [comment]
I'm not sure what the plan is for other number types such as dual numbers, but I think the speedip is due to using the fft_pow2 routine that doesn't recursively call itself.

So if all we want is BigFloat, then we could probably rewrite all the function names with the appropriate Base.fft(::Vector{BigFloat}) override.

The speedup for fft_gen comes from computing the Wks and Wns differently.

Cheers,

Mikael

**Comment by goretkin** [comment]
Yes, I agree that the speedup should mostly come from the reduced memory allocations.
It seems then that we could generalize `function fft_pow2!(data::Vector{BigFloat})` by replacing `big(pi)` with convert(T,pi)  and `big(0.0)`, `big(1.0)` with zero(T) and one(T).

(as a side note, Numerical Recipes is apparently not great about licensing: http://www.astro.umd.edu/~bjw/software/boycottnr.html )

**Comment by MikaelSlevinsky** [comment]
So I did that for fft_pow2 and I changed fft_gen to be overrides of Base.fft since the types are different from `FFTW.fftwNumber`s.

Thanks for drawing the NR license to my attention. I found an FFT in the GNU scientific library (c_radix2.c) which has the same steps and similar notation to the NR routine. I'm not sure which one came first, but I made a change to the trigonometric recurrence for the better, so I'd like to think it's different.

**Pull request merged**
